import { body } from "@/lib/fonts";
import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@repo/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(body.variable, "text-ds-foreground")}>
      <body>{children}</body>
    </html>
  );
}
